EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: nva6112002@gmail.com
EMAIL_PASSWORD: cgbd hpkm evmr gkrb
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}

CLOUDINARY_NAME: dtvnsczg8
CLOUDINARY_API_KEY: 552227585661646
CLOUDINARY_API_SECRET: KtUM0R1ebrS_--wfjX1DnBjpF8Y

MONGODB_HOST: 127.0.0.1
MONGODB_DB_NAME: drinks
MONGODB_PORT: 27027

SERVER_PORT: 7000
ACCESS_TOKEN_KEY: mysecretkey
REFRESH_TOKEN_KEY: refreshtoken
ACTIVE_PROFILE: prod

KAFKA_BOOTSTRAP_SERVER: localhost:9092