ACTIVE_PROFILE: dev

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: nva6112002@gmail.com
EMAIL_PASSWORD: cgbd hpkm evmr gkrb
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}

CLOUDINARY_NAME: dtvnsczg8
CLOUDINARY_API_KEY: 552227585661646
CLOUDINARY_API_SECRET: KtUM0R1ebrS_--wfjX1DnBjpF8Y

MONGODB_HOST: mongodb
MONGODB_DB_NAME: drinks
MONGODB_PORT: 27017

REDIS_HOST: redis
REDIS_PORT: 6379

KAFKA_BOOTSTRAP_SERVER: kafka:9092


APP_USERNAME_ADMIN: admin01
APP_PASSWORD_ADMIN: $2a$07$v6ZbFt4l0Vy3XAzAhpEcGeccRJfk0qZK.PdeSqG821GKwPDsPYcvu

SERVER_PORT: 8080
ACCESS_TOKEN_KEY: 67d00928067d4e5ebfef28ae8d01c051cf3128cc90338e77a65b3da0f3a8b173
REFRESH_TOKEN_KEY: 5194ce614037c5bdeae73fa1f01edb481b767763e10ae2caeeeab54790a2c87b
